// Composition OVERLAYS — a community pack applied as a patch on top of the OWB catalogue.
//
// The Renegade Legacy Pack (squarebased.com) rebalances the Legacy factions. Rather than shipping a
// second catalogue per faction, each pack is a small overlay keyed by COMPOSITION id, merged onto the
// base army when that composition is chosen. Two reasons: a pack update stays a regenerated diff
// instead of a hand-merge, and the change remains inspectable — every patched value keeps `_was`, so
// "why is this 180 and not 230" is answerable from the data.
//
// PURE: nothing here fetches, and nothing mutates its inputs. The caller owns loading and caching.
//
// SCOPE of the current overlays is POINTS ONLY (unit points + Big Name points) — see
// `scripts/import-renegade.mjs`. Stat lines, option changes and rules text are deliberately not
// patched: they cannot be extracted from the source document reliably, and a wrong statline is worse
// than an absent one. So an overlay changes what a list COSTS, never what a unit can do.

import type { Category, MagicItem, MagicItemsData, OwbArmy, OwbUnit } from './owbBuilder';

/** Where a pack came from, so the UI can credit it and link out. */
export interface OverlaySource {
  name: string;
  author: string;
  url: string;
  official: boolean;
  terms: string;
}

/** A single patched unit. Only the fields present are replaced; `_was`/`_changed` are provenance and
 *  are never merged into the unit itself. */
export interface OverlayUnitPatch {
  points?: number;
  _was?: number;
  _changed?: string[];
}

export interface CompositionOverlay {
  /** The composition id this overlay belongs to, e.g. `ok-renegade-v2`. */
  id: string;
  label: string;
  /** Slug of the catalogue it patches, e.g. `ogre-kingdoms`. */
  baseArmy: string;
  packVersion: string | null;
  source: OverlaySource;
  status: 'draft' | 'stable';
  /** What the overlay is allowed to touch. Present so a future overlay can widen it explicitly rather
   *  than by accident. */
  scope: 'points-only';
  units: Record<string, OverlayUnitPatch>;
  magicItems: Record<string, MagicItem[]>;
}

/** The overlays that exist, as compositionId → file under `public/renegade/`. A composition without an
 *  entry here is simply an ordinary OWB composition; nothing breaks. */
export const OVERLAY_FILES: Record<string, string> = {
  'ok-renegade-v2': 'ok-renegade-v2.json',
  'de-renegade-v2': 'de-renegade-v2.json',
  'sk-renegade-v2': 'sk-renegade-v2.json',
  'cd-renegade-v2': 'cd-renegade-v2.json',
  'doc-renegade-v2': 'doc-renegade-v2.json',
  'lm-renegade-v2': 'lm-renegade-v2.json',
};

export const hasOverlay = (composition: string): boolean => composition in OVERLAY_FILES;

/** Which overlay compositions an army offers, derived from the overlay ids themselves.
 *
 *  Registered in CODE, never in `public/owb/the-old-world.json`: that file is REGENERATED by
 *  `npm run sync-owb` from upstream Old World Builder, so a composition added there would vanish at the
 *  next data refresh — and vanish quietly, taking the pack out of the picker with it. Overlays are ours,
 *  so their registration lives with them. */
export function overlayCompsFor(armySlug: string, base: CompositionOverlay['baseArmy'][] = []): string[] {
  void base;
  return Object.keys(OVERLAY_FILES).filter((id) => OVERLAY_BASE_ARMY[id] === armySlug);
}

/** overlay id → the army it patches. Kept beside OVERLAY_FILES so adding a pack is one line in each. */
export const OVERLAY_BASE_ARMY: Record<string, string> = {
  'ok-renegade-v2': 'ogre-kingdoms',
  'de-renegade-v2': 'dark-elves',
  'sk-renegade-v2': 'skaven',
  'cd-renegade-v2': 'chaos-dwarfs',
  'doc-renegade-v2': 'daemons-of-chaos',
  'lm-renegade-v2': 'lizardmen',
};

/** Shallow structural check. An overlay arrives over the network and may be stale or half-written; a
 *  bad file must degrade to "no overlay", never to a broken catalogue. */
export function isOverlay(v: unknown): v is CompositionOverlay {
  const o = v as Partial<CompositionOverlay> | null;
  return !!o && typeof o.id === 'string' && typeof o.baseArmy === 'string'
    && !!o.units && typeof o.units === 'object';
}

/**
 * Apply an overlay's unit patches to a catalogue. Returns a NEW army; the input is untouched.
 *
 * Every unit in the result also gains `armyComposition[overlay.id] = { category }`, because the
 * existing engine decides availability and placement from that map (`unitAllowedIn`,
 * `unitCategoryFor`). Without it, choosing the overlay composition would hide every unit that already
 * carries an `armyComposition` map — the composition would look empty rather than patched.
 */
export function applyOverlay(base: OwbArmy, overlay: CompositionOverlay): OwbArmy {
  const out = { ...base } as OwbArmy & Record<string, unknown>;
  for (const [cat, arr] of Object.entries(base as Record<string, unknown>)) {
    if (!Array.isArray(arr)) continue;
    out[cat] = (arr as OwbUnit[]).map((u) => {
      const patch = overlay.units[u.id];
      const comp = { ...(u.armyComposition ?? {}), [overlay.id]: { category: cat as Category } };
      if (!patch) return { ...u, armyComposition: comp };
      // Only real fields are copied over; `_was`/`_changed` stay out of the unit.
      const next: OwbUnit = { ...u, armyComposition: comp };
      if (typeof patch.points === 'number') next.points = patch.points;
      return next;
    });
  }
  return out as OwbArmy;
}

/**
 * Apply an overlay's magic-item changes. Returns NEW items data; the input is untouched.
 *
 * An entry either REPRICES a base item (matched on `name`) or adds a new one. Matching on `name` rather
 * than on display text because `name` is the id the engine stores in `entry.opts` as
 * `magic/<catId>/<itemId>` — repricing by display name would create a second, unreachable item and the
 * player's existing pick would silently keep the old price.
 */
export function applyOverlayItems(items: MagicItemsData, overlay: CompositionOverlay): MagicItemsData {
  const lists = overlay.magicItems;
  if (!lists || Object.keys(lists).length === 0) return items;
  const out: MagicItemsData = { ...items };
  for (const [listId, patches] of Object.entries(lists)) {
    const existing = Array.isArray(items[listId]) ? items[listId] : [];
    const byName = new Map(existing.map((it, i) => [String(it.name), i]));
    const merged = [...existing];
    for (const p of patches) {
      const at = byName.get(String(p.name));
      // Strip provenance so it never reaches the item the UI renders or the engine prices.
      const clean = { ...p } as MagicItem & { _was?: number };
      delete clean._was;
      if (at != null) merged[at] = { ...merged[at], ...clean };
      else merged.push(clean);
    }
    out[listId] = merged;
  }
  return out;
}

/** The provenance of a patched unit's points, for a "why is this different" affordance. */
export function unitPointsProvenance(overlay: CompositionOverlay, unitId: string): { was: number; now: number } | null {
  const p = overlay.units[unitId];
  if (!p || typeof p.points !== 'number' || typeof p._was !== 'number') return null;
  return { was: p._was, now: p.points };
}
