// Composition OVERLAYS — a community pack applied as a patch on top of the OWB catalogue.
//
// The Renegade Legacy Pack (squarebased.com) rebalances the Legacy factions. Rather than shipping a
// second catalogue per faction, each pack is a small overlay keyed by COMPOSITION id, merged onto the
// base army when that composition is chosen. Two reasons: a pack update stays a regenerated diff
// instead of a hand-merge, and the change remains inspectable — every patched value keeps `_was`, so
// "why is this 180 and not 230" is answerable from the data.
//
// PURE: nothing here fetches, and nothing mutates its inputs. The caller owns loading and caching.
//
// SCOPE is POINTS (unit points + Big Name points) and SPECIAL RULES PROSE. Points come from the pack's
// text export (`scripts/import-renegade.mjs`), rules prose from its PDF rendering
// (`scripts/import-renegade-rules.mjs`) — the rules pages are set in two columns, which a text export
// interleaves into nonsense and only the PDF preserves.
//
// Still deliberately NOT patched: stat lines, option prices, and the magic-item TABLES. Those do not
// survive extraction intact — table entries come out attached to their neighbours' names — and a wrong
// statline is worse than an absent one.

import type { Rule } from '../types';
import type { Category, MagicItem, MagicItemsData, OwbArmy, OwbUnit } from './owbBuilder';

/** Where a pack came from, so the UI can credit it and link out. */
export interface OverlaySource {
  name: string;
  author: string;
  url: string;
  official: boolean;
  terms: string;
}

/** One repriced option on a unit.
 *
 *  Keyed by NAME, not by the `<group>/<index>` key the engine stores in `entry.opts`. Indices shift
 *  whenever `npm run sync-owb` regenerates the catalogue, and a shifted index would silently reprice a
 *  DIFFERENT option; a name that no longer exists simply fails to apply, which is the safe direction. */
export interface OverlayOptionPatch {
  /** The option group it lives in — `equipment` | `armor` | `options` | `command` | `mounts`. */
  group: string;
  name_en: string;
  points: number;
  _was?: number;
}

/** A single patched unit. Only the fields present are replaced; `_was`/`_changed` are provenance and
 *  are never merged into the unit itself. */
export interface OverlayUnitPatch {
  points?: number;
  _was?: number;
  _changed?: string[];
  /** Repriced options — command upgrades, weapons, armour, mounts, special-rule buys. */
  options?: OverlayOptionPatch[];
}

/** One special rule as the pack words it. `body` is paragraphs, in order. */
export interface OverlayRule {
  name_en: string;
  body: string[];
  /** The `rules.json` slug this REPLACES while the pack is active, or null when the pack introduces a
   *  rule the app has never had. Replacing in place is what stops the app showing two contradictory
   *  versions of the same rule name. */
  overrides: string | null;
}

export interface CompositionOverlay {
  /** The composition id this overlay belongs to, e.g. `ok-renegade-v2`. */
  id: string;
  label: string;
  /** Slug of the catalogue it patches, e.g. `ogre-kingdoms`. */
  baseArmy: string;
  packVersion: string | null;
  source: OverlaySource;
  status: 'draft' | 'stable';
  /** What the overlay is allowed to touch. Present so a future overlay can widen it explicitly rather
   *  than by accident. */
  scope: 'points-only' | 'points-and-rules';
  units: Record<string, OverlayUnitPatch>;
  magicItems: Record<string, MagicItem[]>;
  /** Special-rule prose, keyed by the pack's own slug. Absent on a points-only overlay. */
  rules?: Record<string, OverlayRule>;
}

/** The overlays that exist, as compositionId → file under `public/renegade/`. A composition without an
 *  entry here is simply an ordinary OWB composition; nothing breaks. */
export const OVERLAY_FILES: Record<string, string> = {
  'ok-renegade-v2': 'ok-renegade-v2.json',
  'de-renegade-v2': 'de-renegade-v2.json',
  'sk-renegade-v2': 'sk-renegade-v2.json',
  'cd-renegade-v2': 'cd-renegade-v2.json',
  'doc-renegade-v2': 'doc-renegade-v2.json',
  'lm-renegade-v2': 'lm-renegade-v2.json',
};

export const hasOverlay = (composition: string): boolean => composition in OVERLAY_FILES;

/** Which overlay compositions an army offers, derived from the overlay ids themselves.
 *
 *  Registered in CODE, never in `public/owb/the-old-world.json`: that file is REGENERATED by
 *  `npm run sync-owb` from upstream Old World Builder, so a composition added there would vanish at the
 *  next data refresh — and vanish quietly, taking the pack out of the picker with it. Overlays are ours,
 *  so their registration lives with them. */
export function overlayCompsFor(armySlug: string, base: CompositionOverlay['baseArmy'][] = []): string[] {
  void base;
  return Object.keys(OVERLAY_FILES).filter((id) => OVERLAY_BASE_ARMY[id] === armySlug);
}

/** overlay id → the army it patches. Kept beside OVERLAY_FILES so adding a pack is one line in each. */
export const OVERLAY_BASE_ARMY: Record<string, string> = {
  'ok-renegade-v2': 'ogre-kingdoms',
  'de-renegade-v2': 'dark-elves',
  'sk-renegade-v2': 'skaven',
  'cd-renegade-v2': 'chaos-dwarfs',
  'doc-renegade-v2': 'daemons-of-chaos',
  'lm-renegade-v2': 'lizardmen',
};

/** Shallow structural check. An overlay arrives over the network and may be stale or half-written; a
 *  bad file must degrade to "no overlay", never to a broken catalogue. */
export function isOverlay(v: unknown): v is CompositionOverlay {
  const o = v as Partial<CompositionOverlay> | null;
  return !!o && typeof o.id === 'string' && typeof o.baseArmy === 'string'
    && !!o.units && typeof o.units === 'object';
}

/**
 * Apply an overlay's unit patches to a catalogue. Returns a NEW army; the input is untouched.
 *
 * Every unit in the result also gains `armyComposition[overlay.id] = { category }`, because the
 * existing engine decides availability and placement from that map (`unitAllowedIn`,
 * `unitCategoryFor`). Without it, choosing the overlay composition would hide every unit that already
 * carries an `armyComposition` map — the composition would look empty rather than patched.
 */
export function applyOverlay(base: OwbArmy, overlay: CompositionOverlay): OwbArmy {
  const out = { ...base } as OwbArmy & Record<string, unknown>;
  for (const [cat, arr] of Object.entries(base as Record<string, unknown>)) {
    if (!Array.isArray(arr)) continue;
    out[cat] = (arr as OwbUnit[]).map((u) => {
      const patch = overlay.units[u.id];
      const comp = { ...(u.armyComposition ?? {}), [overlay.id]: { category: cat as Category } };
      if (!patch) return { ...u, armyComposition: comp };
      // Only real fields are copied over; `_was`/`_changed` stay out of the unit.
      const next: OwbUnit = { ...u, armyComposition: comp };
      if (typeof patch.points === 'number') next.points = patch.points;
      if (patch.options?.length) applyOptionPatches(next, patch.options);
      return next;
    });
  }
  return out as OwbArmy;
}

const normOpt = (s: string): string =>
  String(s).toLowerCase().replace(/\{[^}]*\}/g, '').replace(/[^a-z0-9 ]/g, ' ').replace(/\s+/g, ' ').trim();

/**
 * Reprice options on a unit, in place on the already-copied `unit`.
 *
 * Matches on the option's NAME within its group, one level of nesting included (a mount's sub-options,
 * a Wizard's levels). Arrays are rebuilt rather than mutated, because the caller only shallow-copied the
 * unit — writing into `unit.command[0]` would reach through into the base catalogue and reprice the
 * option for every composition, including the ones this overlay does not apply to.
 */
function applyOptionPatches(unit: OwbUnit, patches: OverlayOptionPatch[]): void {
  const byGroup = new Map<string, Map<string, number>>();
  for (const p of patches) {
    if (typeof p.points !== 'number' || !p.group || !p.name_en) continue;
    if (!byGroup.has(p.group)) byGroup.set(p.group, new Map());
    byGroup.get(p.group)!.set(normOpt(p.name_en), p.points);
  }
  const u = unit as OwbUnit & Record<string, unknown>;
  for (const [group, wanted] of byGroup) {
    const arr = u[group];
    if (!Array.isArray(arr)) continue;
    u[group] = (arr as { name_en?: string; points?: number; options?: unknown[] }[]).map((opt) => {
      const next = { ...opt };
      const hit = wanted.get(normOpt(next.name_en ?? ''));
      if (typeof hit === 'number') next.points = hit;
      if (Array.isArray(next.options)) {
        next.options = (next.options as { name_en?: string; points?: number }[]).map((sub) => {
          const s = wanted.get(normOpt(sub.name_en ?? ''));
          return typeof s === 'number' ? { ...sub, points: s } : sub;
        });
      }
      return next;
    });
  }
}

/**
 * Apply an overlay's magic-item changes. Returns NEW items data; the input is untouched.
 *
 * An entry either REPRICES a base item (matched on `name`) or adds a new one. Matching on `name` rather
 * than on display text because `name` is the id the engine stores in `entry.opts` as
 * `magic/<catId>/<itemId>` — repricing by display name would create a second, unreachable item and the
 * player's existing pick would silently keep the old price.
 */
export function applyOverlayItems(items: MagicItemsData, overlay: CompositionOverlay): MagicItemsData {
  const lists = overlay.magicItems;
  if (!lists || Object.keys(lists).length === 0) return items;
  const out: MagicItemsData = { ...items };
  for (const [listId, patches] of Object.entries(lists)) {
    const existing = Array.isArray(items[listId]) ? items[listId] : [];
    const byName = new Map(existing.map((it, i) => [String(it.name), i]));
    const merged = [...existing];
    for (const p of patches) {
      const at = byName.get(String(p.name));
      // Strip provenance so it never reaches the item the UI renders or the engine prices.
      const clean = { ...p } as MagicItem & { _was?: number };
      delete clean._was;
      if (at != null) merged[at] = { ...merged[at], ...clean };
      else merged.push(clean);
    }
    out[listId] = merged;
  }
  return out;
}

/** Plain paragraphs as the Contentful-shaped rich text the rule sheet already renders. */
const richText = (paras: string[]): Rule['body'] => ({
  nodeType: 'document',
  content: paras.map((p) => ({
    nodeType: 'paragraph',
    content: [{ nodeType: 'text', value: p, marks: [] }],
  })),
});

/**
 * Fold an overlay's special rules into the app's rules, returning a NEW record; the input is untouched.
 *
 * An OVERRIDING rule takes the base rule's slug AND its name. Keeping the base name matters more than it
 * looks: `buildRuleIndex` maps a rule's NAME to its slug, and that index is how a unit's "Aquatic" label
 * finds its rule. Renaming it "Aquatic (Renegade V2)" would leave nothing in the index answering to
 * "Aquatic", so every unit carrying the label would silently stop resolving.
 *
 * A NEW rule gets its own `-renegade-v2` slug — no base entry is displaced — and resolves by name as
 * usual, because no base rule answers to that name.
 */
export function applyOverlayRules(rules: Record<string, Rule>, overlay: CompositionOverlay): Record<string, Rule> {
  const packed = overlay.rules;
  if (!packed || Object.keys(packed).length === 0) return rules;
  const out = { ...rules };
  for (const [slug, r] of Object.entries(packed)) {
    const base = r.overrides ? rules[r.overrides] : undefined;
    const targetSlug = r.overrides ?? `${slug}-renegade-v2`;
    // The reader has to be able to tell which wording they are looking at — the pack's version of a
    // rule can be materially different from the one in the book.
    const paras = [...r.body, `— ${overlay.label}, ${overlay.source.name} (${overlay.source.author}). ${base ? 'Replaces the standard rule' : 'New rule'} for this army composition.`];
    out[targetSlug] = {
      slug: targetSlug,
      name: base?.name ?? r.name_en,
      order: base?.order ?? null,
      // NOT inherited from the base rule: this is the pack's wording, and citing the rulebook page it
      // replaced would send the reader to a page that says something else.
      pageReference: null,
      parentSlug: base?.parentSlug ?? 'special-rules',
      body: richText(paras),
      bodyIndex: r.body.join(' '),
      childSlugs: [],
      prevSlug: null,
      nextSlug: null,
      crossRefSlugs: [],
      // No inline links are reconstructed from plain prose, so nothing is claimed here.
      refSlugs: [],
    };
  }
  return out;
}

/** The provenance of a patched unit's points, for a "why is this different" affordance. */
export function unitPointsProvenance(overlay: CompositionOverlay, unitId: string): { was: number; now: number } | null {
  const p = overlay.units[unitId];
  if (!p || typeof p.points !== 'number' || typeof p._was !== 'number') return null;
  return { was: p._was, now: p.points };
}
